### ISSUE TITLE
Long term support?

### ISSUE THREAD

**Issue by growdigital** [simonmiddleton/resourcespace#8]
Are you planning on supporting this mirror for the long term? It's exactly what I'm looking for, as I only have git to be able to upgrade on my shared server. Thanks 🙂

**Comment by simonmiddleton** [comment]
Hi. Yes, I expect to keep this mirror for the foreseeable future. Currently I don't sync regularly though, it only tends to be when there's a new release out, or a problem comes up.

**Comment by growdigital** [comment]
Ah, brilliant, thank you. Really appreciated, saves me a lot of headache 🙂
